# Generated by Django 5.1.2 on 2024-10-27 13:01

import django.core.validators
import furry_funnies.author_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), furry_funnies.author_profile.validators.AuthorNameValidator()], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), furry_funnies.author_profile.validators.AuthorNameValidator()], verbose_name='Last Name')),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[furry_funnies.author_profile.validators.AuthorPasscodeValidator()])),
                ('pets_number', models.PositiveSmallIntegerField(verbose_name='Pets Number')),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Profile Image URL')),
            ],
        ),
    ]
